[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.49.1"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "0f601d095cdfe465edc51882323d19e6b333c419"}
